name: MyHWProj

on:
  push:
    branches: [ myhwproj-p2 ]
  pull_request:
    branches: [ myhwproj-p2 ]

jobs:
  build:
    
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        cd hwproj_p2
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Test with pytest
      run: |
        cd hwproj_p2
        bash run_tests.sh
